print("Hi all, I am Anshu Puspam")
print("I very good QA tester")
print('STUDENT NAME : Anshu Puspam \nE-MAIL : anshu.pushpam@gmail.com \nMAJOR:Computer science')
print('COMPUTER PROGRAMMING EXPERIENCE : None')
print('The computer can compute: 12345679 * 9')
print('and the product is:', 12345679 * 9)
